name: Build Mod

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PATH (for Android)
      run: echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build mod jar (Desktop + Android)
      run: |
        chmod +x ./gradlew
        ./gradlew deploy

    - name: Upload built jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar

    - name: Upload to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/${{ github.event.repository.name }}.jar
